In [170]:
from __future__ import division
import numpy as np
import pandas as pd
from pandas import DataFrame
from matplotlib import pyplot as plt
import matplotlib.patches as patches
import seaborn as sns
#%matplotlib inline

AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'

In [171]:
#import dataset
df = pd.read_csv (r'C:\Users\alberto\Desktop\Jan-1-2019-Oct-31-2019.csv')
df

,Placement,Day,Reach,Impressions,Frequency,Currency,Amount Spent (SEK),"CPM (Cost per 1,000 Impressions)",CPC (All),"Cost per 1,000 People Reached",Cost per 3-Second Video View,Cost per 10-Second Video View,CPC (Cost per Link Click),Cost per Post Engagement
0,instream_video,2019-10-30,33.0,107,3.242424,SEK,16.453722,153.773100,16.453722,498.597628,4.113430,5.484574,16.453722,3.290744
1,facebook_stories,2019-10-30,NaN,11,NaN,SEK,1.489302,135.391049,NaN,NaN,NaN,NaN,NaN,NaN
2,messenger_stories,2019-10-30,NaN,4,NaN,SEK,0.846658,211.664430,NaN,NaN,NaN,NaN,NaN,NaN
3,feed,2019-10-30,125851.0,142359,1.131171,SEK,12948.844391,90.959085,7.142220,102.890278,1.905924,6.576356,13.308165,1.606357
4,instagram_stories,2019-10-30,42634.0,43652,1.023878,SEK,1430.117099,32.761777,9.109026,33.544052,1.659069,4.307582,10.071247,1.421588
5,right_hand_column,2019-10-30,976.0,1890,1.936475,SEK,18.106234,9.580018,2.263279,18.551470,NaN,NaN,2.263279,2.263279
6,instagram_explore,2019-10-30,4577.0,4571,0.998689,SEK,102.088560,22.333966,10.208856,22.304689,0.155386,0.420118,25.522140,0.153517
7,rewarded_video,2019-10-30,33.0,59,1.787879,SEK,2.499170,42.358820,NaN,75.732436,0.043845,0.043845,NaN,0.043845
8,instant_article,2019-10-30,327.0,327,1.000000,SEK,5.926604,18.124171,2.963302,18.124171,1.975535,NaN,2.963302,1.185321
9,marketplace,2019-10-30,1041.0,1227,1.178674,SEK,31.469145,25.647225,NaN,30.229727,0.111593,0.552090,NaN,0.111593
10,an_classic,2019-10-30,325.0,656,2.018462,SEK,20.829820,31.752775,5.207455,64.091754,0.145663,0.671930,5.207455,0.141699
11,messenger_inbox,2019-10-30,1757.0,2274,1.294252,SEK,28.816965,12.672368,7.204241,16.401232,NaN,NaN,9.605655,9.605655
12,suggested_video,2019-10-30,195.0,212,1.087179,SEK,5.977608,28.196262,NaN,30.654398,0.249067,1.494402,NaN,0.249067
13,facebook_stories,2019-10-29,NaN,43,NaN,SEK,5.259990,122.325351,NaN,NaN,1.753330,2.629995,NaN,1.753330
14,messenger_stories,2019-10-29,NaN,12,NaN,SEK,2.239996,186.666314,NaN,NaN,0.447999,2.239996,NaN,0.447999
15,instream_video,2019-10-29,NaN,153,NaN,SEK,20.419961,133.463800,6.806654,NaN,0.887824,1.134442,6.806654,0.785383
16,rewarded_video,2019-10-29,NaN,59,NaN,SEK,5.709989,96.779478,NaN,NaN,0.100175,0.101964,NaN,0.100175
17,instagram_stories,2019-10-29,72128.0,72773,1.008942,SEK,1850.926507,25.434248,9.073169,25.661692,0.993519,2.933323,10.952228,0.909993
18,feed,2019-10-29,228095.0,287449,1.260216,SEK,24109.514508,83.874059,6.225023,105.699443,1.456152,4.737574,11.574419,1.265392
19,instagram_explore,2019-10-29,11520.0,12034,1.044618,SEK,230.939564,19.190590,10.997122,20.046837,0.170687,0.538321,15.395971,0.167712
20,marketplace,2019-10-29,4096.0,4232,1.033203,SEK,78.799851,18.620003,6.061527,19.238245,0.075842,0.260066,6.061527,0.074905
21,messenger_inbox,2019-10-29,3050.0,3050,1.000000,SEK,38.239928,12.537681,4.248881,12.537681,NaN,NaN,4.248881,4.248881
22,right_hand_column,2019-10-29,3584.0,6093,1.700056,SEK,86.459837,14.190027,4.803324,24.123838,NaN,NaN,5.085873,5.085873
23,suggested_video,2019-10-29,1088.0,1089,1.000919,SEK,27.629948,25.371853,6.907487,25.395173,0.281938,0.812646,13.814974,0.276299
24,instant_article,2019-10-29,640.0,763,1.192187,SEK,12.979976,17.011763,6.489988,20.281212,0.540832,2.163329,NaN,0.540832
25,an_classic,2019-10-29,640.0,1153,1.801562,SEK,29.279945,25.394575,4.182849,45.749914,0.076052,0.336551,4.182849,0.074694
26,feed,2019-10-28,270461.0,340910,1.260477,SEK,24229.762547,71.073781,6.138779,89.586900,1.412649,4.691145,11.129886,1.229313
27,right_hand_column,2019-10-28,2752.0,5635,2.047602,SEK,106.609087,18.919093,5.330454,38.738767,NaN,NaN,5.330454,5.330454
28,instagram_stories,2019-10-28,125631.0,132895,1.057820,SEK,3283.411888,24.706813,10.591651,26.135364,1.496541,4.292042,11.810834,1.326631
29,instagram_explore,2019-10-28,8825.0,8825,1.000000,SEK,167.468566,18.976608,6.202539,18.976608,0.129519,0.394973,11.962040,0.126870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2934,instagram_stories,2019-01-04,86784.0,89212,1.027978,SEK,1396.840000,15.657535,19.134795,16.095594,0.392702,1.426803,19.954857,0.385017
2935,right_hand_column,2019-01-04,NaN,129,NaN,SEK,1.330000,10.310078,NaN,NaN,NaN,NaN,NaN,NaN
2936,an_classic,2019-01-04,NaN,2,NaN,SEK,0.010000,5.000000,NaN,NaN,0.010000,NaN,NaN,0.010000
2937,feed,2019-01-04,191488.0,231250,1.207647,SEK,6567.370000,28.399438,3.546096,34.296509,0.475655,2.364064,5.786229,0.434091
2938,instant_article,2019-01-04,790.0,790,1.000000,SEK,14.160000,17.924051,14.160000,17.924051,NaN,NaN,14.160000,14.160000
2939,marketplace,2019-01-04,1408.0,2139,1.519176,SEK,26.630000,12.449743,8.876667,18.913352,NaN,NaN,8.876667,8.876667
2940,messenger_inbox,2019-01-04,3456.0,4031,1.166377,SEK,110.040000,27.298437,2.974054,31.840278,NaN,NaN,2.974054,2.974054
2941,facebook_stories,2019-01-04,NaN,13,NaN,SEK,0.690000,53.076923,0.690000,NaN,NaN,NaN,0.690000,0.690000
2942,instagram_stories,2019-01-03,67520.0,68934,1.020942,SEK,1037.217372,15.046528,12.805153,15.361632,0.403587,1.416964,14.817391,0.392885
2943,right_hand_column,2019-01-03,64.0,199,3.109375,SEK,1.229997,6.180889,NaN,19.218701,NaN,NaN,NaN,NaN
2944,messenger_inbox,2019-01-03,2496.0,2697,1.080529,SEK,67.569829,25.053700,2.815410,27.071246,NaN,NaN,2.937819,2.937819
2945,instant_article,2019-01-03,1008.0,1008,1.000000,SEK,18.549953,18.402731,9.274976,18.402731,NaN,NaN,9.274976,9.274976
2946,facebook_stories,2019-01-03,NaN,12,NaN,SEK,0.459999,38.333236,0.459999,NaN,NaN,NaN,0.459999,0.459999
2947,marketplace,2019-01-03,2074.0,2074,1.000000,SEK,24.529938,11.827357,8.176646,11.827357,NaN,NaN,8.176646,8.176646
2948,feed,2019-01-03,206975.0,256878,1.241106,SEK,6745.482912,26.259481,3.526128,32.590810,0.409388,2.146876,5.418059,0.376906
2949,right_hand_column,2019-01-02,64.0,208,3.250000,SEK,1.610000,7.740385,1.610000,25.156250,NaN,NaN,1.610000,1.610000
2950,messenger_inbox,2019-01-02,512.0,559,1.091797,SEK,9.090000,16.261181,2.272500,17.753906,NaN,NaN,2.272500,2.272500
2951,instant_article,2019-01-02,1108.0,1108,1.000000,SEK,13.640000,12.310469,4.546667,12.310469,6.820000,NaN,13.640000,3.410000
2952,rewarded_video,2019-01-02,NaN,1,NaN,SEK,0.040000,40.000000,NaN,NaN,0.040000,0.040000,NaN,0.040000
2953,facebook_stories,2019-01-02,NaN,7,NaN,SEK,0.210000,30.000000,NaN,NaN,NaN,NaN,NaN,NaN
2954,feed,2019-01-02,234624.0,283436,1.208044,SEK,6939.830000,24.484646,3.874835,29.578517,0.394600,2.118385,5.941635,0.366585
2955,instagram_stories,2019-01-02,62976.0,67082,1.065199,SEK,919.360000,13.705018,18.026667,14.598577,0.378337,1.271591,19.560851,0.371009
2956,marketplace,2019-01-02,1536.0,1714,1.115885,SEK,19.810000,11.557760,9.905000,12.897135,NaN,NaN,9.905000,9.905000
2957,right_hand_column,2019-01-01,64.0,100,1.562500,SEK,0.710000,7.100000,NaN,11.093750,NaN,NaN,NaN,NaN
2958,messenger_inbox,2019-01-01,192.0,205,1.067708,SEK,2.230000,10.878049,NaN,11.614583,NaN,NaN,NaN,NaN
2959,marketplace,2019-01-01,1535.0,1535,1.000000,SEK,16.510000,10.755700,16.510000,10.755700,NaN,NaN,16.510000,16.510000
2960,instant_article,2019-01-01,1216.0,1216,1.000000,SEK,13.900000,11.430921,4.633333,11.430921,NaN,NaN,4.633333,4.633333
2961,instagram_stories,2019-01-01,107456.0,116145,1.080861,SEK,1345.640000,11.585862,10.851935,12.522707,0.301308,1.091354,11.403729,0.293551
2962,feed,2019-01-01,259328.0,306899,1.183440,SEK,6593.960000,21.485766,2.922855,25.427104,0.340720,1.892641,4.152368,0.312155
2963,facebook_stories,2019-01-01,37.0,37,1.000000,SEK,1.400000,37.837838,NaN,37.837838,NaN,NaN,NaN,NaN

In [163]:
#interested categories
df_feed = df[df['Placement']=='feed']
df_instagram_stories = df[df['Placement']=='instagram_stories']

In [165]:
#feed
df_feed['Day'] = pd.to_datetime(df_feed['Day'], errors='coerce')
df_feed['weekday'] = df_feed.Day.dt.weekday_name
df_feed['week'] = df_feed['Day'].dt.week
df_feed

C:\Users\alberto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\alberto\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\alberto\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Placement,Day,Reach,Impressions,Frequency,Currency,Amount Spent (SEK),"CPM (Cost per 1,000 Impressions)",CPC (All),"Cost per 1,000 People Reached",Cost per 3-Second Video View,Cost per 10-Second Video View,CPC (Cost per Link Click),Cost per Post Engagement,weekday,week
3,feed,2019-10-30,125851.0,142359,1.131171,SEK,12948.844391,90.959085,7.142220,102.890278,1.905924,6.576356,13.308165,1.606357,Wednesday,44
18,feed,2019-10-29,228095.0,287449,1.260216,SEK,24109.514508,83.874059,6.225023,105.699443,1.456152,4.737574,11.574419,1.265392,Tuesday,44
26,feed,2019-10-28,270461.0,340910,1.260477,SEK,24229.762547,71.073781,6.138779,89.586900,1.412649,4.691145,11.129886,1.229313,Monday,44
42,feed,2019-10-27,398463.0,568857,1.427628,SEK,59853.199656,105.216600,8.773556,150.210182,3.291712,11.208464,17.557407,2.688098,Sunday,43
62,feed,2019-10-26,392959.0,530629,1.350342,SEK,63512.470667,119.692800,9.833174,161.626202,3.695164,12.763760,19.997629,3.024259,Saturday,43
74,feed,2019-10-25,320769.0,456029,1.421674,SEK,51566.230000,113.076646,8.731160,160.758147,3.038670,10.665198,18.253533,2.523550,Friday,43
89,feed,2019-10-24,304448.0,419991,1.379516,SEK,42693.700000,101.653845,8.161671,140.233143,3.025776,9.354448,15.424025,2.435465,Thursday,43
94,feed,2019-10-23,191232.0,232659,1.216632,SEK,19663.870000,84.517986,5.890914,102.827299,3.717178,8.155898,10.188534,2.541208,Wednesday,43
108,feed,2019-10-22,182470.0,222790,1.220968,SEK,18235.209242,81.849317,5.454744,99.935382,3.233193,7.598004,9.825005,2.319706,Tuesday,43
123,feed,2019-10-21,192640.0,242019,1.256328,SEK,18847.720000,77.877026,4.821622,97.839078,2.983178,6.944628,8.803232,2.147154,Monday,43
136,feed,2019-10-20,191360.0,245213,1.281422,SEK,19234.860000,78.441437,4.840176,100.516618,2.421916,5.660642,8.759044,1.845248,Sunday,42
141,feed,2019-10-19,185152.0,232837,1.257545,SEK,19969.460000,85.765836,4.786544,107.854412,2.180786,5.256504,8.530312,1.690322,Saturday,42
155,feed,2019-10-18,181504.0,238088,1.311751,SEK,20468.348943,85.969679,5.041465,112.770787,2.182592,5.195012,8.814965,1.700029,Friday,42
169,feed,2019-10-17,206465.0,258578,1.252406,SEK,21842.816831,84.472835,5.353632,105.794284,2.369326,6.015648,9.243680,1.836766,Thursday,42
177,feed,2019-10-16,195711.0,241476,1.233840,SEK,21550.935614,89.246698,5.541511,110.116118,4.069285,8.843223,9.926732,2.768975,Wednesday,42
190,feed,2019-10-15,195833.0,251468,1.284094,SEK,22255.152684,88.500933,5.144511,113.643526,4.745235,9.609306,9.147206,2.988874,Tuesday,42
205,feed,2019-10-14,219709.0,278481,1.267499,SEK,23779.886337,85.391414,4.673720,108.233556,4.227535,8.704204,8.600321,2.709959,Monday,42
217,feed,2019-10-13,200448.0,242926,1.211915,SEK,16717.490000,68.817212,3.896851,83.400633,1.843163,3.721614,7.284309,1.433010,Sunday,41
231,feed,2019-10-12,203200.0,246233,1.211777,SEK,18207.660000,73.944841,4.400111,89.604626,1.524674,3.556184,7.791040,1.245905,Saturday,41
241,feed,2019-10-11,185728.0,234152,1.260725,SEK,18002.210000,76.882581,4.681979,96.927819,1.618176,3.891528,8.205201,1.314030,Friday,41
257,feed,2019-10-10,197056.0,241267,1.224358,SEK,18796.110000,77.905847,5.309636,95.384611,1.649939,4.022279,9.010599,1.360460,Thursday,41
262,feed,2019-10-09,183424.0,226416,1.234386,SEK,17586.950000,77.675385,5.268709,95.881400,1.831974,4.525721,9.657853,1.491178,Wednesday,41
275,feed,2019-10-08,185792.0,222846,1.199438,SEK,16949.200000,76.057905,4.828832,91.226748,1.600038,3.953627,8.696357,1.312874,Tuesday,41
287,feed,2019-10-07,197568.0,240726,1.218446,SEK,17193.280000,71.422613,4.679717,87.024619,1.536486,3.684801,8.987601,1.272069,Monday,41
310,feed,2019-10-06,198080.0,248916,1.256644,SEK,17860.730000,71.754046,4.716327,90.169275,1.404919,3.267008,8.497017,1.175512,Sunday,40
319,feed,2019-10-05,211136.0,266340,1.261462,SEK,19966.850000,74.967523,4.968114,94.568667,1.373330,3.369932,8.874156,1.161674,Saturday,40
325,feed,2019-10-04,203776.0,256707,1.259751,SEK,19924.220000,77.614635,5.189951,97.775106,1.525942,3.653809,9.597408,1.281795,Friday,40
337,feed,2019-10-03,178944.0,217177,1.213659,SEK,17572.940000,80.915290,5.023711,98.203572,1.530477,3.739719,9.337375,1.278776,Thursday,40
359,feed,2019-10-02,177600.0,218877,1.232416,SEK,16987.720000,77.613089,4.863361,95.651577,1.422757,3.587692,9.905376,1.211678,Wednesday,40
364,feed,2019-10-01,198208.0,240887,1.215324,SEK,17382.820000,72.161719,4.621861,87.699891,1.326933,3.678904,9.168154,1.130222,Tuesday,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2750,feed,2019-01-30,328749.0,423950,1.289586,SEK,15215.192361,35.889120,4.901802,46.282095,0.727756,2.584102,13.116545,0.672198,Wednesday,5
2754,feed,2019-01-29,295103.0,373003,1.263976,SEK,13508.722054,36.216122,4.138702,45.776295,0.795848,2.435320,12.554574,0.721312,Tuesday,5
2764,feed,2019-01-28,264831.0,321479,1.213902,SEK,13066.032012,40.643501,3.525643,49.337245,0.730640,2.132185,10.263969,0.657047,Monday,5
2773,feed,2019-01-27,230271.0,276728,1.201749,SEK,11934.343272,43.126620,5.059069,51.827383,0.747344,1.856330,9.222831,0.670959,Sunday,4
2781,feed,2019-01-26,319614.0,423173,1.324013,SEK,16052.533754,37.933738,5.969704,50.224752,0.586437,2.003061,11.417165,0.545893,Saturday,4
2783,feed,2019-01-25,334334.0,441446,1.320374,SEK,16377.931821,37.100646,6.222618,48.986737,0.578011,2.027474,11.599102,0.539262,Friday,4
2797,feed,2019-01-24,297278.0,392632,1.320757,SEK,14785.310379,37.656916,5.786814,49.735636,0.652456,2.470807,9.969865,0.599907,Thursday,4
2799,feed,2019-01-23,272705.0,355882,1.305007,SEK,13130.907411,36.896801,5.446249,48.150593,0.736533,2.708521,8.482498,0.666916,Wednesday,4
2806,feed,2019-01-22,219709.0,268870,1.223755,SEK,10700.700664,39.798790,4.935748,48.703971,1.007030,3.294551,8.094327,0.875599,Tuesday,4
2813,feed,2019-01-21,270399.0,338923,1.253418,SEK,12283.260690,36.242039,5.135142,45.426428,0.602623,2.058532,9.005323,0.555075,Monday,4
2826,feed,2019-01-20,217151.0,264025,1.215859,SEK,11249.211248,42.606614,4.625498,51.803635,0.767969,2.227567,8.626696,0.690093,Sunday,3
2831,feed,2019-01-19,342847.0,453497,1.322739,SEK,16123.261952,35.553183,5.971579,47.027572,0.469683,1.881361,10.864732,0.444669,Saturday,3
2835,feed,2019-01-18,318015.0,427182,1.343276,SEK,15628.044985,36.584044,6.273804,49.142478,0.529513,2.173278,12.238093,0.500610,Friday,3
2841,feed,2019-01-17,363201.0,476362,1.311566,SEK,16494.645411,34.626283,6.274114,45.414648,0.490343,2.040154,12.766753,0.465977,Thursday,3
2849,feed,2019-01-16,327039.0,426239,1.303328,SEK,15116.004629,35.463683,5.621422,46.220801,0.551860,2.146855,11.565421,0.518542,Wednesday,3
2860,feed,2019-01-15,260735.0,338200,1.297102,SEK,13727.253148,40.589158,4.421016,52.648295,0.575977,1.556025,9.447525,0.532952,Tuesday,3
2868,feed,2019-01-14,273088.0,345079,1.263618,SEK,12356.120000,35.806641,4.238806,45.245928,0.524186,1.531877,8.468896,0.484953,Monday,3
2870,feed,2019-01-13,294847.0,339557,1.151638,SEK,11903.530876,35.056061,3.563931,40.371891,0.465819,1.294847,5.166463,0.420411,Sunday,2
2877,feed,2019-01-12,450304.0,592463,1.315696,SEK,18749.500000,31.646702,3.882688,41.637427,0.311128,0.927734,5.448852,0.289358,Saturday,2
2890,feed,2019-01-11,396416.0,514774,1.298570,SEK,17325.480000,33.656478,4.395099,43.705299,0.418328,1.626500,6.590141,0.389284,Friday,2
2895,feed,2019-01-10,361472.0,506122,1.400169,SEK,16254.900000,32.116565,5.540184,44.968628,0.499536,2.022257,9.401330,0.467888,Thursday,2
2901,feed,2019-01-09,339840.0,468631,1.378975,SEK,13904.570000,29.670615,5.050697,40.915048,0.659484,2.706749,8.088755,0.598612,Wednesday,2
2907,feed,2019-01-08,227712.0,304065,1.335305,SEK,9518.420000,31.303899,3.931607,41.800256,1.068885,4.834139,6.274502,0.878894,Tuesday,2
2915,feed,2019-01-07,203264.0,237094,1.166434,SEK,6721.310000,28.348714,4.048982,33.066898,0.422458,2.216060,6.929186,0.394327,Monday,2
2922,feed,2019-01-06,204288.0,244740,1.198015,SEK,6368.660000,26.022146,3.781865,31.174910,0.378276,1.922905,5.918829,0.352288,Sunday,1
2927,feed,2019-01-05,189248.0,224917,1.188478,SEK,6461.380000,28.727842,3.438733,34.142395,0.480865,2.380759,5.574961,0.436757,Saturday,1
2937,feed,2019-01-04,191488.0,231250,1.207647,SEK,6567.370000,28.399438,3.546096,34.296509,0.475655,2.364064,5.786229,0.434091,Friday,1
2948,feed,2019-01-03,206975.0,256878,1.241106,SEK,6745.482912,26.259481,3.526128,32.590810,0.409388,2.146876,5.418059,0.376906,Thursday,1
2954,feed,2019-01-02,234624.0,283436,1.208044,SEK,6939.830000,24.484646,3.874835,29.578517,0.394600,2.118385,5.941635,0.366585,Wednesday,1
2962,feed,2019-01-01,259328.0,306899,1.183440,SEK,6593.960000,21.485766,2.922855,25.427104,0.340720,1.892641,4.152368,0.312155,Tuesday,1

In [158]:
#df_feed.groupby(['week'])

In [160]:
#feed amount weekly
weekly_df_feed_amount = df_feed.groupby(['week'])[['Amount Spent (SEK)']]
weekly_df_feed_amount = weekly_df_feed_amount.sum()
weekly_df_feed_amount

      Amount Spent (SEK)
week
1           39676.682912
2           94377.710876
3          100694.541373
4           95264.987992
5          103705.226138
6          107543.828192
7          115421.224084
8          120510.762700
9          147546.984258
10         109629.373854
11          96925.406590
12          97222.715951
13          93499.902949
14          73358.846127
15          95668.292436
16         104161.597764
17         102325.249232
18          85273.126092
19          90539.164223
20          90015.217600
21          98160.771308
22          96340.542313
23          90898.114812
24         162584.766098
25         165399.096476
26         107248.828842
27          92189.890141
28         103664.492461
29          90246.354336
30          72271.655286
31          98259.737934
32          89721.070002
33          84699.801425
34         106709.806605
35         100239.938984
36         123172.651169
37         129017.848917
38         145387.416905
39         171833.214219
40         131409.100000
41         123452.900000
42         149101.460409
43         274372.399565
44          61288.121446

In [166]:
#feed impressions weekly (/1000)
weekly_df_feed_impressions = df_feed.groupby(['week'])[['Impressions']]
weekly_df_feed_impressions = weekly_df_feed_impressions.sum()
weekly_df_feed_impressions = weekly_df_feed_impressions / 1000
weekly_df_feed_impressions

      Impressions
week
1        1548.120
2        2962.706
3        2730.584
4        2497.654
5        2654.529
6        2551.866
7        2760.063
8        2525.129
9        2554.655
10       2194.657
11       1828.414
12       1875.191
13       1596.804
14       1086.616
15       1414.383
16       1477.905
17       1414.666
18       1189.473
19       1095.572
20       1101.266
21       1066.958
22       1194.039
23       1439.025
24       3132.281
25       3642.153
26       2263.386
27       2245.706
28       2081.128
29       1766.002
30       1638.580
31       1929.423
32       1540.812
33       1213.073
34       1341.971
35       1188.135
36       1681.304
37       2089.095
38       2030.900
39       2140.149
40       1758.478
41       1654.566
42       1746.141
43       2672.974
44        770.718

In [197]:
#feed day of the week (amount and impressions /1000)
#df_feed.groupby(['weekday'])
day_feed_amount = df_feed.groupby(['weekday'])[['Amount Spent (SEK)']]
day_feed_amount = day_feed_amount.sum()

In [198]:
day_feed_impressions = df_feed.groupby(['weekday'])[['Impressions']]
day_feed_impressions = feed_impressions.sum()
day_feed_impressions = feed_impressions / 1000

In [199]:
#instagram stories
df_instagram_stories['Day'] = pd.to_datetime(df_instagram_stories['Day'], errors='coerce')
df_instagram_stories['weekday'] = df_instagram_stories.Day.dt.weekday_name
df_instagram_stories['week'] = df_instagram_stories['Day'].dt.week

C:\Users\alberto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\alberto\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\alberto\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [200]:
#df_instagram_stories.groupby(['week'])

In [206]:
#instagram stories weekly amount
weekly_df_instagram_stories_amount = df_instagram_stories.groupby(['week'])[['Amount Spent (SEK)']]
weekly_df_instagram_stories_amount = weekly_df_instagram_stories_amount.sum()
weekly_df_instagram_stories_amount

      Amount Spent (SEK)
week
1            7627.617372
2            8508.699556
3            8455.244006
4           11036.148119
5           12244.888617
6            9750.193274
7           12440.152844
8           13256.987798
9           21745.252333
10          19769.842515
11          17611.231825
12          14949.745202
13          19641.045344
14          13026.918806
15          13382.800773
16          14072.763135
17          12340.955936
18          12255.881992
19          10763.814148
20           8969.052763
21           9096.602851
22          10941.737296
23           8768.767815
24           9209.949036
25           7715.570301
26          19411.599581
27          20658.401935
28          23184.415271
29          20513.750522
30          15890.825938
31          29684.942591
32          24074.903140
33          14683.238748
34          14220.432784
35          11657.856674
36          10608.971099
37          11140.702041
38          16475.332803
39          19837.839243
40          18816.720000
41          19590.580000
42          23397.673563
43          24218.859915
44           6564.455494

In [202]:
# instagram stories weekly impressions/1000
weekly_df_instagram_stories_impressions = df_instagram_stories.groupby(['week'])[['Impressions']]
weekly_df_instagram_stories_impressions = weekly_df_instagram_stories_impressions.sum()
weekly_df_instagram_stories_impressions = weekly_df_instagram_stories_impressions /1000

In [203]:
df_instagram_stories.groupby(['weekday'])

In [204]:
#day_df_instagram_stories_amount
day_df_instagram_stories_amount = df_instagram_stories.groupby(['weekday'])[['Amount Spent (SEK)']]
day_df_instagram_stories_amount = day_df_instagram_stories_amount.sum()

In [153]:
#day_df_instagram_stories_impressions /1000
day_df_instagram_stories_impressions = df_instagram_stories.groupby(['weekday'])[['Impressions']]
day_df_instagram_stories_impressions = day_df_instagram_stories_impressions.sum()
day_df_instagram_stories_impressions = day_df_instagram_stories_impressions / 1000

In [194]:
CPM_feed_weekly= []

for x in range(len(weekly_df_feed_amount)):
    weekly_df_feed_amount.iloc[x,0] / weekly_df_feed_impressions.iloc[x,0]
    CPM_feed_weekly.append(weekly_df_feed_amount.iloc[x,0] / weekly_df_feed_impressions.iloc[x,0])
CPM_feed_weekly

[25.628945373808232,
 31.855240066489888,
 36.87655877771569,
 38.141787450043125,
 39.0672794073638,
 42.14321135683849,
 41.81832953965906,
 47.724596525650774,
 57.756129206585626,
 49.9528508800783,
 53.01064561422632,
 51.84683370963278,
 58.55440176076712,
 67.51128837321556,
 67.63959439265037,
 70.47922414762789,
 72.33173712550526,
 71.68983750988883,
 82.64099869574068,
 81.73794305783525,
 92.00059543904261,
 80.68458594107898,
 63.16645979873873,
 51.90618788613155,
 45.412451502303725,
 47.38424150460416,
 41.051629260833785,
 49.8116850388251,
 51.10206802474177,
 44.10627206854106,
 50.927006640783276,
 58.229732116442506,
 69.82250979532147,
 79.51722250712571,
 84.36746580503056,
 73.2601904048881,
 61.75777019085299,
 71.58767881471267,
 80.29030418852612,
 74.7288848652073,
 74.6134635910565,
 85.3891297489779,
 102.64686434112716,
 79.52081234075239]

In [208]:
weekly_CPM_instagram_stories = []
for x in range(len(weekly_df_instagram_stories_amount)):
    weekly_df_instagram_stories_amount.iloc[x,0] / weekly_df_instagram_stories_impressions.iloc[x,0]
    weekly_CPM_instagram_stories.append(weekly_df_instagram_stories_amount.iloc[x,0] / weekly_df_instagram_stories_impressions.iloc[x,0])
weekly_CPM_instagram_stories

[13.94889301620625,
 15.633232689565839,
 19.262562465081206,
 20.97198031892717,
 21.950656942296764,
 22.26590044674787,
 21.600712682084477,
 22.16646651730163,
 23.174789204947164,
 26.038886779489573,
 29.046196591870938,
 26.565848357474014,
 28.731906874752227,
 26.386572288660005,
 27.765089227740194,
 31.110204299549906,
 24.245064302792287,
 24.363342500685825,
 32.17852798997318,
 29.02343076591765,
 36.46049914009267,
 36.640883581462795,
 17.42136993554975,
 19.284499314883483,
 19.79127786159699,
 24.55063715257577,
 21.706728382030146,
 28.37148960024377,
 23.867768721580035,
 18.87128049421422,
 30.44840592058269,
 29.240713852976008,
 39.13422302716936,
 44.37824840511551,
 48.603970222218514,
 21.99789973019375,
 21.129227316226185,
 26.986047475696665,
 31.992025704522106,
 30.616604186191818,
 27.83029562598554,
 29.560507231648554,
 26.817116720129953,
 26.329438046807315]

In [215]:
daily_CPM_feed = []
for x in range(len(day_feed_amount)):
    day_feed_amount.iloc[x,0] / day_feed_impressions.iloc[x,0]
    daily_CPM_feed.append(day_feed_amount.iloc[x,0] / day_feed_impressions.iloc[x,0])

daily_CPM_feed

[57354.668169385746,
 57954.58756988986,
 56223.13542543286,
 60952.27424813473,
 56339.88458359799,
 60437.354270598604,
 58043.169944443536]

In [216]:
daily_CPM_instagram = []
for x in range(len(day_df_instagram_stories_amount)):
    day_df_instagram_stories_amount.iloc[x,0] / day_df_instagram_stories_impressions.iloc[x,0]
    daily_CPM_instagram.append(day_df_instagram_stories_amount.iloc[x,0] / day_df_instagram_stories_impressions.iloc[x,0])

daily_CPM_instagram

[26.70876201680323,
 25.242053394225174,
 25.174062596634343,
 22.902709712459874,
 26.465746091787597,
 26.573896184872144,
 26.941262222694508]